build:
    tests:
        override:
            -
                command: 'phpunit --coverage-clover=coverage-report'
                coverage:
                    file: 'coverage-report'
                    format: 'php-clover'